spring:
  application:
    name: gateway

client:
  order:
    url: http://localhost:8081

server:
  port: 8080
  tomcat:
    threads:
      max: 50
    accept-count: 50

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: INFO
    com.demo.gateway: INFO
    ALERT: WARN
