global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
    env: codespaces

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - alert-rules.yml

scrape_configs:
  - job_name: 'java-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - host.docker.internal:28080
          - host.docker.internal:28081
          - host.docker.internal:28082
        labels:
          env: codespaces

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
